### ISSUE TITLE
/entrypoint.sh: line 62: syntax error: unexpected "(" with v1.1

### ISSUE THREAD

**Issue by RoFz** [mdegis/bandit-action#7]
I'm working on a PR so that this action could support GHES via the GITHUB_API_URL variable instead of the static API URL in formatter.py, but came up with the following error with the latest release.

When using v1.1:

```
      - uses: mdegis/bandit-action@v1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: 'components/hello-world'
          level: low
          confidence: low
```

I get this:

```
/entrypoint.sh: line 62: syntax error: unexpected "("
```

Version 1.0 works fine.

Is the error above expected with v1.1 or am I missing something in my config?
